version: "3.9"

x-default-env: &default-env
  env_file:
    - .env-preprod

services:
  db:
    image: postgres:16
    restart: unless-stopped
    <<: *default-env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - preprod_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 30s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile-prod
    restart: unless-stopped
    <<: *default-env
    depends_on:
      - db
    command: ["/bin/bash", "/code/deploy/preprod/entrypoint.sh"]
    volumes:
      - staticfiles:/code/static
      - mediafiles:/code/media
      - gunicorn-sock:/run

  nginx:
    image: nginx:1.26
    restart: unless-stopped
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./infra/preprod/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infra/preprod/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./infra/preprod/nginx/htpasswd:/etc/nginx/htpasswd:ro
      - staticfiles:/var/www/static:ro
      - mediafiles:/var/www/media:ro
      - gunicorn-sock:/run:ro

volumes:
  preprod_postgres_data:
  staticfiles:
  mediafiles:
  gunicorn-sock:
